### ISSUE TITLE
After make deploy, eventmesh-runtime-0-a pod cannot be started

### ISSUE THREAD

**Issue by ColeSu-n** [apache/eventmesh#5136]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Question

I cloned the v1.10.0 tag, and then entered the eventmesh-operator directory and executed `make deploy`. I found that the log of the eventmesh-runtime-0-a sts instance showed `exec /bin/bash: exec format error`

```
root@master:~/apache-eventmesh-1.10.0-src/eventmesh-operator# kubectl get po 
NAME                                        READY   STATUS             RESTARTS      AGE
connector-rocketmq-0                        0/1     CrashLoopBackOff   4 (75s ago)   3m13s
eventmesh-runtime-0-a-0                     0/1     CrashLoopBackOff   0             3m9s
```

eventmesh-runtime-0-a-0.yaml 
```
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: eventmesh-runtime-0-a
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      app: eventmesh-runtime
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eventmesh-runtime
    spec:
      volumes:
        - name: runtime-config
          configMap:
            name: runtime-config
            items:
              - key: rocketmq.properties
                path: rocketmq.properties
              - key: eventmesh.properties
                path: eventmesh.properties
              - key: server.env
                path: server.env
              - key: log4j2.xml
                path: log4j2.xml
            defaultMode: 420
      containers:
        - name: eventmesh-runtime
          image: 'alonexc/eventmesh-runtime:runtime-1.9.0'
          ports:
            - name: tcp
              containerPort: 10000
              protocol: TCP
            - name: http
              containerPort: 10105
              protocol: TCP
            - name: grpc
              containerPort: 10205
              protocol: TCP
          resources: 
              limits: 
                 cpu: "8"
                 memory: 8Gi
          volumeMounts:
            - name: runtime-config
              mountPath: /data/app/eventmesh/conf
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirstWithHostNet
      securityContext: {}
      schedulerName: default-scheduler
  serviceName: ''
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
```

![img_v3_02ha_023202c9-9ac7-4766-a63c-953d870b6fag](https://github.com/user-attachments/assets/3a98814d-ba1d-4829-adee-fecdfaaf3763)

我的架构是amd64
